// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class OracleAddedEvent extends ethereum.Event {
  get params(): OracleAddedEvent__Params {
    return new OracleAddedEvent__Params(this);
  }
}

export class OracleAddedEvent__Params {
  _event: OracleAddedEvent;

  constructor(event: OracleAddedEvent) {
    this._event = event;
  }

  get oracle(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get name(): string {
    return this._event.parameters[1].value.toString();
  }
}

export class OracleJobAddedEvent extends ethereum.Event {
  get params(): OracleJobAddedEvent__Params {
    return new OracleJobAddedEvent__Params(this);
  }
}

export class OracleJobAddedEvent__Params {
  _event: OracleJobAddedEvent;

  constructor(event: OracleJobAddedEvent) {
    this._event = event;
  }

  get oracle(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get name(): string {
    return this._event.parameters[1].value.toString();
  }

  get id(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class OracleJobRemovedEvent extends ethereum.Event {
  get params(): OracleJobRemovedEvent__Params {
    return new OracleJobRemovedEvent__Params(this);
  }
}

export class OracleJobRemovedEvent__Params {
  _event: OracleJobRemovedEvent;

  constructor(event: OracleJobRemovedEvent) {
    this._event = event;
  }

  get oracle(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get name(): string {
    return this._event.parameters[1].value.toString();
  }

  get id(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class OracleNameChangedEvent extends ethereum.Event {
  get params(): OracleNameChangedEvent__Params {
    return new OracleNameChangedEvent__Params(this);
  }
}

export class OracleNameChangedEvent__Params {
  _event: OracleNameChangedEvent;

  constructor(event: OracleNameChangedEvent) {
    this._event = event;
  }

  get oracle(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get name(): string {
    return this._event.parameters[1].value.toString();
  }
}

export class OracleRemovedEvent extends ethereum.Event {
  get params(): OracleRemovedEvent__Params {
    return new OracleRemovedEvent__Params(this);
  }
}

export class OracleRemovedEvent__Params {
  _event: OracleRemovedEvent;

  constructor(event: OracleRemovedEvent) {
    this._event = event;
  }

  get oracle(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class OracleStorage__getOracleJobResult {
  value0: Bytes;
  value1: BigInt;

  constructor(value0: Bytes, value1: BigInt) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromFixedBytes(this.value0));
    map.set("value1", ethereum.Value.fromUnsignedBigInt(this.value1));
    return map;
  }
}

export class OracleStorage extends ethereum.SmartContract {
  static bind(address: Address): OracleStorage {
    return new OracleStorage("OracleStorage", address);
  }

  octobay(): Address {
    let result = super.call("octobay", "octobay():(address)", []);

    return result[0].toAddress();
  }

  try_octobay(): ethereum.CallResult<Address> {
    let result = super.tryCall("octobay", "octobay():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  oracleJobNames(param0: Address, param1: BigInt): string {
    let result = super.call(
      "oracleJobNames",
      "oracleJobNames(address,uint256):(string)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1)
      ]
    );

    return result[0].toString();
  }

  try_oracleJobNames(
    param0: Address,
    param1: BigInt
  ): ethereum.CallResult<string> {
    let result = super.tryCall(
      "oracleJobNames",
      "oracleJobNames(address,uint256):(string)",
      [
        ethereum.Value.fromAddress(param0),
        ethereum.Value.fromUnsignedBigInt(param1)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  oracles(param0: Address): string {
    let result = super.call("oracles", "oracles(address):(string)", [
      ethereum.Value.fromAddress(param0)
    ]);

    return result[0].toString();
  }

  try_oracles(param0: Address): ethereum.CallResult<string> {
    let result = super.tryCall("oracles", "oracles(address):(string)", [
      ethereum.Value.fromAddress(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  registeredOracles(param0: BigInt): Address {
    let result = super.call(
      "registeredOracles",
      "registeredOracles(uint256):(address)",
      [ethereum.Value.fromUnsignedBigInt(param0)]
    );

    return result[0].toAddress();
  }

  try_registeredOracles(param0: BigInt): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "registeredOracles",
      "registeredOracles(uint256):(address)",
      [ethereum.Value.fromUnsignedBigInt(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  getOracleName(_oracle: Address): string {
    let result = super.call(
      "getOracleName",
      "getOracleName(address):(string)",
      [ethereum.Value.fromAddress(_oracle)]
    );

    return result[0].toString();
  }

  try_getOracleName(_oracle: Address): ethereum.CallResult<string> {
    let result = super.tryCall(
      "getOracleName",
      "getOracleName(address):(string)",
      [ethereum.Value.fromAddress(_oracle)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toString());
  }

  getOracleJob(
    _oracle: Address,
    _job: string
  ): OracleStorage__getOracleJobResult {
    let result = super.call(
      "getOracleJob",
      "getOracleJob(address,string):(bytes32,uint256)",
      [ethereum.Value.fromAddress(_oracle), ethereum.Value.fromString(_job)]
    );

    return new OracleStorage__getOracleJobResult(
      result[0].toBytes(),
      result[1].toBigInt()
    );
  }

  try_getOracleJob(
    _oracle: Address,
    _job: string
  ): ethereum.CallResult<OracleStorage__getOracleJobResult> {
    let result = super.tryCall(
      "getOracleJob",
      "getOracleJob(address,string):(bytes32,uint256)",
      [ethereum.Value.fromAddress(_oracle), ethereum.Value.fromString(_job)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new OracleStorage__getOracleJobResult(
        value[0].toBytes(),
        value[1].toBigInt()
      )
    );
  }

  oracleExists(_oracle: Address): boolean {
    let result = super.call("oracleExists", "oracleExists(address):(bool)", [
      ethereum.Value.fromAddress(_oracle)
    ]);

    return result[0].toBoolean();
  }

  try_oracleExists(_oracle: Address): ethereum.CallResult<boolean> {
    let result = super.tryCall("oracleExists", "oracleExists(address):(bool)", [
      ethereum.Value.fromAddress(_oracle)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  oracleJobExists(_oracle: Address, _jobName: string): boolean {
    let result = super.call(
      "oracleJobExists",
      "oracleJobExists(address,string):(bool)",
      [ethereum.Value.fromAddress(_oracle), ethereum.Value.fromString(_jobName)]
    );

    return result[0].toBoolean();
  }

  try_oracleJobExists(
    _oracle: Address,
    _jobName: string
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "oracleJobExists",
      "oracleJobExists(address,string):(bool)",
      [ethereum.Value.fromAddress(_oracle), ethereum.Value.fromString(_jobName)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }
}

export class RenounceOwnershipCall extends ethereum.Call {
  get inputs(): RenounceOwnershipCall__Inputs {
    return new RenounceOwnershipCall__Inputs(this);
  }

  get outputs(): RenounceOwnershipCall__Outputs {
    return new RenounceOwnershipCall__Outputs(this);
  }
}

export class RenounceOwnershipCall__Inputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall__Outputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class SetOctobayCall extends ethereum.Call {
  get inputs(): SetOctobayCall__Inputs {
    return new SetOctobayCall__Inputs(this);
  }

  get outputs(): SetOctobayCall__Outputs {
    return new SetOctobayCall__Outputs(this);
  }
}

export class SetOctobayCall__Inputs {
  _call: SetOctobayCall;

  constructor(call: SetOctobayCall) {
    this._call = call;
  }

  get _octobay(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetOctobayCall__Outputs {
  _call: SetOctobayCall;

  constructor(call: SetOctobayCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}

export class AddOracleCall extends ethereum.Call {
  get inputs(): AddOracleCall__Inputs {
    return new AddOracleCall__Inputs(this);
  }

  get outputs(): AddOracleCall__Outputs {
    return new AddOracleCall__Outputs(this);
  }
}

export class AddOracleCall__Inputs {
  _call: AddOracleCall;

  constructor(call: AddOracleCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _name(): string {
    return this._call.inputValues[1].value.toString();
  }

  get _jobNames(): Array<string> {
    return this._call.inputValues[2].value.toStringArray();
  }

  get _jobs(): Array<AddOracleCall_jobsStruct> {
    return this._call.inputValues[3].value.toTupleArray<
      AddOracleCall_jobsStruct
    >();
  }
}

export class AddOracleCall__Outputs {
  _call: AddOracleCall;

  constructor(call: AddOracleCall) {
    this._call = call;
  }
}

export class AddOracleCall_jobsStruct extends ethereum.Tuple {
  get id(): Bytes {
    return this[0].toBytes();
  }

  get fee(): BigInt {
    return this[1].toBigInt();
  }
}

export class RemoveOracleCall extends ethereum.Call {
  get inputs(): RemoveOracleCall__Inputs {
    return new RemoveOracleCall__Inputs(this);
  }

  get outputs(): RemoveOracleCall__Outputs {
    return new RemoveOracleCall__Outputs(this);
  }
}

export class RemoveOracleCall__Inputs {
  _call: RemoveOracleCall;

  constructor(call: RemoveOracleCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class RemoveOracleCall__Outputs {
  _call: RemoveOracleCall;

  constructor(call: RemoveOracleCall) {
    this._call = call;
  }
}

export class ChangeOracleNameCall extends ethereum.Call {
  get inputs(): ChangeOracleNameCall__Inputs {
    return new ChangeOracleNameCall__Inputs(this);
  }

  get outputs(): ChangeOracleNameCall__Outputs {
    return new ChangeOracleNameCall__Outputs(this);
  }
}

export class ChangeOracleNameCall__Inputs {
  _call: ChangeOracleNameCall;

  constructor(call: ChangeOracleNameCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _name(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class ChangeOracleNameCall__Outputs {
  _call: ChangeOracleNameCall;

  constructor(call: ChangeOracleNameCall) {
    this._call = call;
  }
}

export class AddOracleJobCall extends ethereum.Call {
  get inputs(): AddOracleJobCall__Inputs {
    return new AddOracleJobCall__Inputs(this);
  }

  get outputs(): AddOracleJobCall__Outputs {
    return new AddOracleJobCall__Outputs(this);
  }
}

export class AddOracleJobCall__Inputs {
  _call: AddOracleJobCall;

  constructor(call: AddOracleJobCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _jobName(): string {
    return this._call.inputValues[1].value.toString();
  }

  get _job(): AddOracleJobCall_jobStruct {
    return this._call.inputValues[2].value.toTuple() as AddOracleJobCall_jobStruct;
  }
}

export class AddOracleJobCall__Outputs {
  _call: AddOracleJobCall;

  constructor(call: AddOracleJobCall) {
    this._call = call;
  }
}

export class AddOracleJobCall_jobStruct extends ethereum.Tuple {
  get id(): Bytes {
    return this[0].toBytes();
  }

  get fee(): BigInt {
    return this[1].toBigInt();
  }
}

export class RemoveOracleJobCall extends ethereum.Call {
  get inputs(): RemoveOracleJobCall__Inputs {
    return new RemoveOracleJobCall__Inputs(this);
  }

  get outputs(): RemoveOracleJobCall__Outputs {
    return new RemoveOracleJobCall__Outputs(this);
  }
}

export class RemoveOracleJobCall__Inputs {
  _call: RemoveOracleJobCall;

  constructor(call: RemoveOracleJobCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _jobName(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class RemoveOracleJobCall__Outputs {
  _call: RemoveOracleJobCall;

  constructor(call: RemoveOracleJobCall) {
    this._call = call;
  }
}
