// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class ChainlinkCancelled extends ethereum.Event {
  get params(): ChainlinkCancelled__Params {
    return new ChainlinkCancelled__Params(this);
  }
}

export class ChainlinkCancelled__Params {
  _event: ChainlinkCancelled;

  constructor(event: ChainlinkCancelled) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }
}

export class ChainlinkFulfilled extends ethereum.Event {
  get params(): ChainlinkFulfilled__Params {
    return new ChainlinkFulfilled__Params(this);
  }
}

export class ChainlinkFulfilled__Params {
  _event: ChainlinkFulfilled;

  constructor(event: ChainlinkFulfilled) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }
}

export class ChainlinkRequested extends ethereum.Event {
  get params(): ChainlinkRequested__Params {
    return new ChainlinkRequested__Params(this);
  }
}

export class ChainlinkRequested__Params {
  _event: ChainlinkRequested;

  constructor(event: ChainlinkRequested) {
    this._event = event;
  }

  get id(): Bytes {
    return this._event.parameters[0].value.toBytes();
  }
}

export class OwnershipTransferred extends ethereum.Event {
  get params(): OwnershipTransferred__Params {
    return new OwnershipTransferred__Params(this);
  }
}

export class OwnershipTransferred__Params {
  _event: OwnershipTransferred;

  constructor(event: OwnershipTransferred) {
    this._event = event;
  }

  get previousOwner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get newOwner(): Address {
    return this._event.parameters[1].value.toAddress();
  }
}

export class SetDepositStorageEvent extends ethereum.Event {
  get params(): SetDepositStorageEvent__Params {
    return new SetDepositStorageEvent__Params(this);
  }
}

export class SetDepositStorageEvent__Params {
  _event: SetDepositStorageEvent;

  constructor(event: SetDepositStorageEvent) {
    this._event = event;
  }

  get depositStorage(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class SetEthUSDPriceFeedEvent extends ethereum.Event {
  get params(): SetEthUSDPriceFeedEvent__Params {
    return new SetEthUSDPriceFeedEvent__Params(this);
  }
}

export class SetEthUSDPriceFeedEvent__Params {
  _event: SetEthUSDPriceFeedEvent;

  constructor(event: SetEthUSDPriceFeedEvent) {
    this._event = event;
  }

  get ethUsdPriceFeed(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class SetOctobayGovNFTEvent extends ethereum.Event {
  get params(): SetOctobayGovNFTEvent__Params {
    return new SetOctobayGovNFTEvent__Params(this);
  }
}

export class SetOctobayGovNFTEvent__Params {
  _event: SetOctobayGovNFTEvent;

  constructor(event: SetOctobayGovNFTEvent) {
    this._event = event;
  }

  get octobayGovNFT(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class SetOctobayGovernorEvent extends ethereum.Event {
  get params(): SetOctobayGovernorEvent__Params {
    return new SetOctobayGovernorEvent__Params(this);
  }
}

export class SetOctobayGovernorEvent__Params {
  _event: SetOctobayGovernorEvent;

  constructor(event: SetOctobayGovernorEvent) {
    this._event = event;
  }

  get octobayGovernor(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class SetOracleStorageEvent extends ethereum.Event {
  get params(): SetOracleStorageEvent__Params {
    return new SetOracleStorageEvent__Params(this);
  }
}

export class SetOracleStorageEvent__Params {
  _event: SetOracleStorageEvent;

  constructor(event: SetOracleStorageEvent) {
    this._event = event;
  }

  get oracleStorage(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class SetUserAddressStorageEvent extends ethereum.Event {
  get params(): SetUserAddressStorageEvent__Params {
    return new SetUserAddressStorageEvent__Params(this);
  }
}

export class SetUserAddressStorageEvent__Params {
  _event: SetUserAddressStorageEvent;

  constructor(event: SetUserAddressStorageEvent) {
    this._event = event;
  }

  get addressStorage(): Address {
    return this._event.parameters[0].value.toAddress();
  }
}

export class Octobay__issueWithdrawRequestsResult {
  value0: string;
  value1: Address;

  constructor(value0: string, value1: Address) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromString(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    return map;
  }
}

export class Octobay__tempGovernanceReqsResult {
  value0: boolean;
  value1: Address;
  value2: string;
  value3: i32;
  value4: i32;
  value5: Address;

  constructor(
    value0: boolean,
    value1: Address,
    value2: string,
    value3: i32,
    value4: i32,
    value5: Address
  ) {
    this.value0 = value0;
    this.value1 = value1;
    this.value2 = value2;
    this.value3 = value3;
    this.value4 = value4;
    this.value5 = value5;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromBoolean(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    map.set("value2", ethereum.Value.fromString(this.value2));
    map.set(
      "value3",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value3))
    );
    map.set(
      "value4",
      ethereum.Value.fromUnsignedBigInt(BigInt.fromI32(this.value4))
    );
    map.set("value5", ethereum.Value.fromAddress(this.value5));
    return map;
  }
}

export class Octobay__userAddressRegistrationsResult {
  value0: string;
  value1: Address;

  constructor(value0: string, value1: Address) {
    this.value0 = value0;
    this.value1 = value1;
  }

  toMap(): TypedMap<string, ethereum.Value> {
    let map = new TypedMap<string, ethereum.Value>();
    map.set("value0", ethereum.Value.fromString(this.value0));
    map.set("value1", ethereum.Value.fromAddress(this.value1));
    return map;
  }
}

export class Octobay__createGovernanceTokenInput_newGovReqStruct extends ethereum.Tuple {
  get name(): string {
    return this[0].toString();
  }

  get symbol(): string {
    return this[1].toString();
  }

  get projectId(): string {
    return this[2].toString();
  }

  get newProposalShare(): i32 {
    return this[3].toI32();
  }

  get minQuorum(): i32 {
    return this[4].toI32();
  }
}

export class Octobay extends ethereum.SmartContract {
  static bind(address: Address): Octobay {
    return new Octobay("Octobay", address);
  }

  depositStorage(): Address {
    let result = super.call("depositStorage", "depositStorage():(address)", []);

    return result[0].toAddress();
  }

  try_depositStorage(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "depositStorage",
      "depositStorage():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  issueWithdrawRequests(param0: Bytes): Octobay__issueWithdrawRequestsResult {
    let result = super.call(
      "issueWithdrawRequests",
      "issueWithdrawRequests(bytes32):(string,address)",
      [ethereum.Value.fromFixedBytes(param0)]
    );

    return new Octobay__issueWithdrawRequestsResult(
      result[0].toString(),
      result[1].toAddress()
    );
  }

  try_issueWithdrawRequests(
    param0: Bytes
  ): ethereum.CallResult<Octobay__issueWithdrawRequestsResult> {
    let result = super.tryCall(
      "issueWithdrawRequests",
      "issueWithdrawRequests(bytes32):(string,address)",
      [ethereum.Value.fromFixedBytes(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new Octobay__issueWithdrawRequestsResult(
        value[0].toString(),
        value[1].toAddress()
      )
    );
  }

  octobayGovNFT(): Address {
    let result = super.call("octobayGovNFT", "octobayGovNFT():(address)", []);

    return result[0].toAddress();
  }

  try_octobayGovNFT(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "octobayGovNFT",
      "octobayGovNFT():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  octobayGovernor(): Address {
    let result = super.call(
      "octobayGovernor",
      "octobayGovernor():(address)",
      []
    );

    return result[0].toAddress();
  }

  try_octobayGovernor(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "octobayGovernor",
      "octobayGovernor():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  oracleStorage(): Address {
    let result = super.call("oracleStorage", "oracleStorage():(address)", []);

    return result[0].toAddress();
  }

  try_oracleStorage(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "oracleStorage",
      "oracleStorage():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  owner(): Address {
    let result = super.call("owner", "owner():(address)", []);

    return result[0].toAddress();
  }

  try_owner(): ethereum.CallResult<Address> {
    let result = super.tryCall("owner", "owner():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  tempGovernanceReqs(param0: Bytes): Octobay__tempGovernanceReqsResult {
    let result = super.call(
      "tempGovernanceReqs",
      "tempGovernanceReqs(bytes32):(bool,address,string,uint16,uint16,address)",
      [ethereum.Value.fromFixedBytes(param0)]
    );

    return new Octobay__tempGovernanceReqsResult(
      result[0].toBoolean(),
      result[1].toAddress(),
      result[2].toString(),
      result[3].toI32(),
      result[4].toI32(),
      result[5].toAddress()
    );
  }

  try_tempGovernanceReqs(
    param0: Bytes
  ): ethereum.CallResult<Octobay__tempGovernanceReqsResult> {
    let result = super.tryCall(
      "tempGovernanceReqs",
      "tempGovernanceReqs(bytes32):(bool,address,string,uint16,uint16,address)",
      [ethereum.Value.fromFixedBytes(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new Octobay__tempGovernanceReqsResult(
        value[0].toBoolean(),
        value[1].toAddress(),
        value[2].toString(),
        value[3].toI32(),
        value[4].toI32(),
        value[5].toAddress()
      )
    );
  }

  userAddressRegistrations(
    param0: Bytes
  ): Octobay__userAddressRegistrationsResult {
    let result = super.call(
      "userAddressRegistrations",
      "userAddressRegistrations(bytes32):(string,address)",
      [ethereum.Value.fromFixedBytes(param0)]
    );

    return new Octobay__userAddressRegistrationsResult(
      result[0].toString(),
      result[1].toAddress()
    );
  }

  try_userAddressRegistrations(
    param0: Bytes
  ): ethereum.CallResult<Octobay__userAddressRegistrationsResult> {
    let result = super.tryCall(
      "userAddressRegistrations",
      "userAddressRegistrations(bytes32):(string,address)",
      [ethereum.Value.fromFixedBytes(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(
      new Octobay__userAddressRegistrationsResult(
        value[0].toString(),
        value[1].toAddress()
      )
    );
  }

  userAddressStorage(): Address {
    let result = super.call(
      "userAddressStorage",
      "userAddressStorage():(address)",
      []
    );

    return result[0].toAddress();
  }

  try_userAddressStorage(): ethereum.CallResult<Address> {
    let result = super.tryCall(
      "userAddressStorage",
      "userAddressStorage():(address)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  registerUserAddress(_oracle: Address, _githubUserId: string): Bytes {
    let result = super.call(
      "registerUserAddress",
      "registerUserAddress(address,string):(bytes32)",
      [
        ethereum.Value.fromAddress(_oracle),
        ethereum.Value.fromString(_githubUserId)
      ]
    );

    return result[0].toBytes();
  }

  try_registerUserAddress(
    _oracle: Address,
    _githubUserId: string
  ): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "registerUserAddress",
      "registerUserAddress(address,string):(bytes32)",
      [
        ethereum.Value.fromAddress(_oracle),
        ethereum.Value.fromString(_githubUserId)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  withdrawIssueDeposit(_oracle: Address, _issueId: string): Bytes {
    let result = super.call(
      "withdrawIssueDeposit",
      "withdrawIssueDeposit(address,string):(bytes32)",
      [ethereum.Value.fromAddress(_oracle), ethereum.Value.fromString(_issueId)]
    );

    return result[0].toBytes();
  }

  try_withdrawIssueDeposit(
    _oracle: Address,
    _issueId: string
  ): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "withdrawIssueDeposit",
      "withdrawIssueDeposit(address,string):(bytes32)",
      [ethereum.Value.fromAddress(_oracle), ethereum.Value.fromString(_issueId)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  createGovernanceToken(
    _oracle: Address,
    _newGovReq: Octobay__createGovernanceTokenInput_newGovReqStruct
  ): Bytes {
    let result = super.call(
      "createGovernanceToken",
      "createGovernanceToken(address,(string,string,string,uint16,uint16)):(bytes32)",
      [
        ethereum.Value.fromAddress(_oracle),
        ethereum.Value.fromTuple(_newGovReq)
      ]
    );

    return result[0].toBytes();
  }

  try_createGovernanceToken(
    _oracle: Address,
    _newGovReq: Octobay__createGovernanceTokenInput_newGovReqStruct
  ): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "createGovernanceToken",
      "createGovernanceToken(address,(string,string,string,uint16,uint16)):(bytes32)",
      [
        ethereum.Value.fromAddress(_oracle),
        ethereum.Value.fromTuple(_newGovReq)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _link(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _userAddressStorage(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _oracleStorage(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get _depositStorage(): Address {
    return this._call.inputValues[3].value.toAddress();
  }

  get _octobayGovernor(): Address {
    return this._call.inputValues[4].value.toAddress();
  }

  get _octobayGovNFT(): Address {
    return this._call.inputValues[5].value.toAddress();
  }

  get _ethUSDPriceFeed(): Address {
    return this._call.inputValues[6].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall extends ethereum.Call {
  get inputs(): RenounceOwnershipCall__Inputs {
    return new RenounceOwnershipCall__Inputs(this);
  }

  get outputs(): RenounceOwnershipCall__Outputs {
    return new RenounceOwnershipCall__Outputs(this);
  }
}

export class RenounceOwnershipCall__Inputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class RenounceOwnershipCall__Outputs {
  _call: RenounceOwnershipCall;

  constructor(call: RenounceOwnershipCall) {
    this._call = call;
  }
}

export class TransferOwnershipCall extends ethereum.Call {
  get inputs(): TransferOwnershipCall__Inputs {
    return new TransferOwnershipCall__Inputs(this);
  }

  get outputs(): TransferOwnershipCall__Outputs {
    return new TransferOwnershipCall__Outputs(this);
  }
}

export class TransferOwnershipCall__Inputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }

  get newOwner(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class TransferOwnershipCall__Outputs {
  _call: TransferOwnershipCall;

  constructor(call: TransferOwnershipCall) {
    this._call = call;
  }
}

export class SetUserAddressStorageCall extends ethereum.Call {
  get inputs(): SetUserAddressStorageCall__Inputs {
    return new SetUserAddressStorageCall__Inputs(this);
  }

  get outputs(): SetUserAddressStorageCall__Outputs {
    return new SetUserAddressStorageCall__Outputs(this);
  }
}

export class SetUserAddressStorageCall__Inputs {
  _call: SetUserAddressStorageCall;

  constructor(call: SetUserAddressStorageCall) {
    this._call = call;
  }

  get _userAddressStorage(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetUserAddressStorageCall__Outputs {
  _call: SetUserAddressStorageCall;

  constructor(call: SetUserAddressStorageCall) {
    this._call = call;
  }
}

export class SetOracleStorageCall extends ethereum.Call {
  get inputs(): SetOracleStorageCall__Inputs {
    return new SetOracleStorageCall__Inputs(this);
  }

  get outputs(): SetOracleStorageCall__Outputs {
    return new SetOracleStorageCall__Outputs(this);
  }
}

export class SetOracleStorageCall__Inputs {
  _call: SetOracleStorageCall;

  constructor(call: SetOracleStorageCall) {
    this._call = call;
  }

  get _oracleStorage(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetOracleStorageCall__Outputs {
  _call: SetOracleStorageCall;

  constructor(call: SetOracleStorageCall) {
    this._call = call;
  }
}

export class SetDepositStorageCall extends ethereum.Call {
  get inputs(): SetDepositStorageCall__Inputs {
    return new SetDepositStorageCall__Inputs(this);
  }

  get outputs(): SetDepositStorageCall__Outputs {
    return new SetDepositStorageCall__Outputs(this);
  }
}

export class SetDepositStorageCall__Inputs {
  _call: SetDepositStorageCall;

  constructor(call: SetDepositStorageCall) {
    this._call = call;
  }

  get _depositStorage(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetDepositStorageCall__Outputs {
  _call: SetDepositStorageCall;

  constructor(call: SetDepositStorageCall) {
    this._call = call;
  }
}

export class SetOctobayGovernorCall extends ethereum.Call {
  get inputs(): SetOctobayGovernorCall__Inputs {
    return new SetOctobayGovernorCall__Inputs(this);
  }

  get outputs(): SetOctobayGovernorCall__Outputs {
    return new SetOctobayGovernorCall__Outputs(this);
  }
}

export class SetOctobayGovernorCall__Inputs {
  _call: SetOctobayGovernorCall;

  constructor(call: SetOctobayGovernorCall) {
    this._call = call;
  }

  get _octobayGovernor(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetOctobayGovernorCall__Outputs {
  _call: SetOctobayGovernorCall;

  constructor(call: SetOctobayGovernorCall) {
    this._call = call;
  }
}

export class SetOctobayGovNFTCall extends ethereum.Call {
  get inputs(): SetOctobayGovNFTCall__Inputs {
    return new SetOctobayGovNFTCall__Inputs(this);
  }

  get outputs(): SetOctobayGovNFTCall__Outputs {
    return new SetOctobayGovNFTCall__Outputs(this);
  }
}

export class SetOctobayGovNFTCall__Inputs {
  _call: SetOctobayGovNFTCall;

  constructor(call: SetOctobayGovNFTCall) {
    this._call = call;
  }

  get _octobayGovNFT(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetOctobayGovNFTCall__Outputs {
  _call: SetOctobayGovNFTCall;

  constructor(call: SetOctobayGovNFTCall) {
    this._call = call;
  }
}

export class SetEthUSDPriceFeedCall extends ethereum.Call {
  get inputs(): SetEthUSDPriceFeedCall__Inputs {
    return new SetEthUSDPriceFeedCall__Inputs(this);
  }

  get outputs(): SetEthUSDPriceFeedCall__Outputs {
    return new SetEthUSDPriceFeedCall__Outputs(this);
  }
}

export class SetEthUSDPriceFeedCall__Inputs {
  _call: SetEthUSDPriceFeedCall;

  constructor(call: SetEthUSDPriceFeedCall) {
    this._call = call;
  }

  get _ethUSDPriceFeed(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class SetEthUSDPriceFeedCall__Outputs {
  _call: SetEthUSDPriceFeedCall;

  constructor(call: SetEthUSDPriceFeedCall) {
    this._call = call;
  }
}

export class AddOracleCall extends ethereum.Call {
  get inputs(): AddOracleCall__Inputs {
    return new AddOracleCall__Inputs(this);
  }

  get outputs(): AddOracleCall__Outputs {
    return new AddOracleCall__Outputs(this);
  }
}

export class AddOracleCall__Inputs {
  _call: AddOracleCall;

  constructor(call: AddOracleCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _name(): string {
    return this._call.inputValues[1].value.toString();
  }

  get _jobNames(): Array<string> {
    return this._call.inputValues[2].value.toStringArray();
  }

  get _jobs(): Array<AddOracleCall_jobsStruct> {
    return this._call.inputValues[3].value.toTupleArray<
      AddOracleCall_jobsStruct
    >();
  }
}

export class AddOracleCall__Outputs {
  _call: AddOracleCall;

  constructor(call: AddOracleCall) {
    this._call = call;
  }
}

export class AddOracleCall_jobsStruct extends ethereum.Tuple {
  get id(): Bytes {
    return this[0].toBytes();
  }

  get fee(): BigInt {
    return this[1].toBigInt();
  }
}

export class RemoveOracleCall extends ethereum.Call {
  get inputs(): RemoveOracleCall__Inputs {
    return new RemoveOracleCall__Inputs(this);
  }

  get outputs(): RemoveOracleCall__Outputs {
    return new RemoveOracleCall__Outputs(this);
  }
}

export class RemoveOracleCall__Inputs {
  _call: RemoveOracleCall;

  constructor(call: RemoveOracleCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }
}

export class RemoveOracleCall__Outputs {
  _call: RemoveOracleCall;

  constructor(call: RemoveOracleCall) {
    this._call = call;
  }
}

export class ChangeOracleNameCall extends ethereum.Call {
  get inputs(): ChangeOracleNameCall__Inputs {
    return new ChangeOracleNameCall__Inputs(this);
  }

  get outputs(): ChangeOracleNameCall__Outputs {
    return new ChangeOracleNameCall__Outputs(this);
  }
}

export class ChangeOracleNameCall__Inputs {
  _call: ChangeOracleNameCall;

  constructor(call: ChangeOracleNameCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _name(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class ChangeOracleNameCall__Outputs {
  _call: ChangeOracleNameCall;

  constructor(call: ChangeOracleNameCall) {
    this._call = call;
  }
}

export class AddOracleJobCall extends ethereum.Call {
  get inputs(): AddOracleJobCall__Inputs {
    return new AddOracleJobCall__Inputs(this);
  }

  get outputs(): AddOracleJobCall__Outputs {
    return new AddOracleJobCall__Outputs(this);
  }
}

export class AddOracleJobCall__Inputs {
  _call: AddOracleJobCall;

  constructor(call: AddOracleJobCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _jobName(): string {
    return this._call.inputValues[1].value.toString();
  }

  get _job(): AddOracleJobCall_jobStruct {
    return this._call.inputValues[2].value.toTuple() as AddOracleJobCall_jobStruct;
  }
}

export class AddOracleJobCall__Outputs {
  _call: AddOracleJobCall;

  constructor(call: AddOracleJobCall) {
    this._call = call;
  }
}

export class AddOracleJobCall_jobStruct extends ethereum.Tuple {
  get id(): Bytes {
    return this[0].toBytes();
  }

  get fee(): BigInt {
    return this[1].toBigInt();
  }
}

export class RemoveOracleJobCall extends ethereum.Call {
  get inputs(): RemoveOracleJobCall__Inputs {
    return new RemoveOracleJobCall__Inputs(this);
  }

  get outputs(): RemoveOracleJobCall__Outputs {
    return new RemoveOracleJobCall__Outputs(this);
  }
}

export class RemoveOracleJobCall__Inputs {
  _call: RemoveOracleJobCall;

  constructor(call: RemoveOracleJobCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _jobName(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class RemoveOracleJobCall__Outputs {
  _call: RemoveOracleJobCall;

  constructor(call: RemoveOracleJobCall) {
    this._call = call;
  }
}

export class RegisterUserAddressCall extends ethereum.Call {
  get inputs(): RegisterUserAddressCall__Inputs {
    return new RegisterUserAddressCall__Inputs(this);
  }

  get outputs(): RegisterUserAddressCall__Outputs {
    return new RegisterUserAddressCall__Outputs(this);
  }
}

export class RegisterUserAddressCall__Inputs {
  _call: RegisterUserAddressCall;

  constructor(call: RegisterUserAddressCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _githubUserId(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class RegisterUserAddressCall__Outputs {
  _call: RegisterUserAddressCall;

  constructor(call: RegisterUserAddressCall) {
    this._call = call;
  }

  get requestId(): Bytes {
    return this._call.outputValues[0].value.toBytes();
  }
}

export class ConfirmRegisterUserAddressCall extends ethereum.Call {
  get inputs(): ConfirmRegisterUserAddressCall__Inputs {
    return new ConfirmRegisterUserAddressCall__Inputs(this);
  }

  get outputs(): ConfirmRegisterUserAddressCall__Outputs {
    return new ConfirmRegisterUserAddressCall__Outputs(this);
  }
}

export class ConfirmRegisterUserAddressCall__Inputs {
  _call: ConfirmRegisterUserAddressCall;

  constructor(call: ConfirmRegisterUserAddressCall) {
    this._call = call;
  }

  get _requestId(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _addressName(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class ConfirmRegisterUserAddressCall__Outputs {
  _call: ConfirmRegisterUserAddressCall;

  constructor(call: ConfirmRegisterUserAddressCall) {
    this._call = call;
  }
}

export class DepositEthForGithubUserCall extends ethereum.Call {
  get inputs(): DepositEthForGithubUserCall__Inputs {
    return new DepositEthForGithubUserCall__Inputs(this);
  }

  get outputs(): DepositEthForGithubUserCall__Outputs {
    return new DepositEthForGithubUserCall__Outputs(this);
  }
}

export class DepositEthForGithubUserCall__Inputs {
  _call: DepositEthForGithubUserCall;

  constructor(call: DepositEthForGithubUserCall) {
    this._call = call;
  }

  get _githubUserId(): string {
    return this._call.inputValues[0].value.toString();
  }
}

export class DepositEthForGithubUserCall__Outputs {
  _call: DepositEthForGithubUserCall;

  constructor(call: DepositEthForGithubUserCall) {
    this._call = call;
  }
}

export class RefundUserDepositCall extends ethereum.Call {
  get inputs(): RefundUserDepositCall__Inputs {
    return new RefundUserDepositCall__Inputs(this);
  }

  get outputs(): RefundUserDepositCall__Outputs {
    return new RefundUserDepositCall__Outputs(this);
  }
}

export class RefundUserDepositCall__Inputs {
  _call: RefundUserDepositCall;

  constructor(call: RefundUserDepositCall) {
    this._call = call;
  }

  get _depositId(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class RefundUserDepositCall__Outputs {
  _call: RefundUserDepositCall;

  constructor(call: RefundUserDepositCall) {
    this._call = call;
  }
}

export class WithdrawUserDepositCall extends ethereum.Call {
  get inputs(): WithdrawUserDepositCall__Inputs {
    return new WithdrawUserDepositCall__Inputs(this);
  }

  get outputs(): WithdrawUserDepositCall__Outputs {
    return new WithdrawUserDepositCall__Outputs(this);
  }
}

export class WithdrawUserDepositCall__Inputs {
  _call: WithdrawUserDepositCall;

  constructor(call: WithdrawUserDepositCall) {
    this._call = call;
  }

  get _depositId(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class WithdrawUserDepositCall__Outputs {
  _call: WithdrawUserDepositCall;

  constructor(call: WithdrawUserDepositCall) {
    this._call = call;
  }
}

export class DepositAndSetGovTokenForIssueCall extends ethereum.Call {
  get inputs(): DepositAndSetGovTokenForIssueCall__Inputs {
    return new DepositAndSetGovTokenForIssueCall__Inputs(this);
  }

  get outputs(): DepositAndSetGovTokenForIssueCall__Outputs {
    return new DepositAndSetGovTokenForIssueCall__Outputs(this);
  }
}

export class DepositAndSetGovTokenForIssueCall__Inputs {
  _call: DepositAndSetGovTokenForIssueCall;

  constructor(call: DepositAndSetGovTokenForIssueCall) {
    this._call = call;
  }

  get _issueId(): string {
    return this._call.inputValues[0].value.toString();
  }

  get _govToken(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class DepositAndSetGovTokenForIssueCall__Outputs {
  _call: DepositAndSetGovTokenForIssueCall;

  constructor(call: DepositAndSetGovTokenForIssueCall) {
    this._call = call;
  }
}

export class SetGovTokenForIssueCall extends ethereum.Call {
  get inputs(): SetGovTokenForIssueCall__Inputs {
    return new SetGovTokenForIssueCall__Inputs(this);
  }

  get outputs(): SetGovTokenForIssueCall__Outputs {
    return new SetGovTokenForIssueCall__Outputs(this);
  }
}

export class SetGovTokenForIssueCall__Inputs {
  _call: SetGovTokenForIssueCall;

  constructor(call: SetGovTokenForIssueCall) {
    this._call = call;
  }

  get _issueId(): string {
    return this._call.inputValues[0].value.toString();
  }

  get _govToken(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class SetGovTokenForIssueCall__Outputs {
  _call: SetGovTokenForIssueCall;

  constructor(call: SetGovTokenForIssueCall) {
    this._call = call;
  }
}

export class DepositEthForIssueCall extends ethereum.Call {
  get inputs(): DepositEthForIssueCall__Inputs {
    return new DepositEthForIssueCall__Inputs(this);
  }

  get outputs(): DepositEthForIssueCall__Outputs {
    return new DepositEthForIssueCall__Outputs(this);
  }
}

export class DepositEthForIssueCall__Inputs {
  _call: DepositEthForIssueCall;

  constructor(call: DepositEthForIssueCall) {
    this._call = call;
  }

  get _issueId(): string {
    return this._call.inputValues[0].value.toString();
  }
}

export class DepositEthForIssueCall__Outputs {
  _call: DepositEthForIssueCall;

  constructor(call: DepositEthForIssueCall) {
    this._call = call;
  }
}

export class RefundIssueDepositCall extends ethereum.Call {
  get inputs(): RefundIssueDepositCall__Inputs {
    return new RefundIssueDepositCall__Inputs(this);
  }

  get outputs(): RefundIssueDepositCall__Outputs {
    return new RefundIssueDepositCall__Outputs(this);
  }
}

export class RefundIssueDepositCall__Inputs {
  _call: RefundIssueDepositCall;

  constructor(call: RefundIssueDepositCall) {
    this._call = call;
  }

  get _depositId(): BigInt {
    return this._call.inputValues[0].value.toBigInt();
  }
}

export class RefundIssueDepositCall__Outputs {
  _call: RefundIssueDepositCall;

  constructor(call: RefundIssueDepositCall) {
    this._call = call;
  }
}

export class WithdrawIssueDepositCall extends ethereum.Call {
  get inputs(): WithdrawIssueDepositCall__Inputs {
    return new WithdrawIssueDepositCall__Inputs(this);
  }

  get outputs(): WithdrawIssueDepositCall__Outputs {
    return new WithdrawIssueDepositCall__Outputs(this);
  }
}

export class WithdrawIssueDepositCall__Inputs {
  _call: WithdrawIssueDepositCall;

  constructor(call: WithdrawIssueDepositCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _issueId(): string {
    return this._call.inputValues[1].value.toString();
  }
}

export class WithdrawIssueDepositCall__Outputs {
  _call: WithdrawIssueDepositCall;

  constructor(call: WithdrawIssueDepositCall) {
    this._call = call;
  }

  get requestId(): Bytes {
    return this._call.outputValues[0].value.toBytes();
  }
}

export class ConfirmWithdrawIssueDepositCall extends ethereum.Call {
  get inputs(): ConfirmWithdrawIssueDepositCall__Inputs {
    return new ConfirmWithdrawIssueDepositCall__Inputs(this);
  }

  get outputs(): ConfirmWithdrawIssueDepositCall__Outputs {
    return new ConfirmWithdrawIssueDepositCall__Outputs(this);
  }
}

export class ConfirmWithdrawIssueDepositCall__Inputs {
  _call: ConfirmWithdrawIssueDepositCall;

  constructor(call: ConfirmWithdrawIssueDepositCall) {
    this._call = call;
  }

  get _requestId(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class ConfirmWithdrawIssueDepositCall__Outputs {
  _call: ConfirmWithdrawIssueDepositCall;

  constructor(call: ConfirmWithdrawIssueDepositCall) {
    this._call = call;
  }
}

export class CreateGovernanceTokenCall extends ethereum.Call {
  get inputs(): CreateGovernanceTokenCall__Inputs {
    return new CreateGovernanceTokenCall__Inputs(this);
  }

  get outputs(): CreateGovernanceTokenCall__Outputs {
    return new CreateGovernanceTokenCall__Outputs(this);
  }
}

export class CreateGovernanceTokenCall__Inputs {
  _call: CreateGovernanceTokenCall;

  constructor(call: CreateGovernanceTokenCall) {
    this._call = call;
  }

  get _oracle(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _newGovReq(): CreateGovernanceTokenCall_newGovReqStruct {
    return this._call.inputValues[1].value.toTuple() as CreateGovernanceTokenCall_newGovReqStruct;
  }
}

export class CreateGovernanceTokenCall__Outputs {
  _call: CreateGovernanceTokenCall;

  constructor(call: CreateGovernanceTokenCall) {
    this._call = call;
  }

  get requestId(): Bytes {
    return this._call.outputValues[0].value.toBytes();
  }
}

export class CreateGovernanceTokenCall_newGovReqStruct extends ethereum.Tuple {
  get name(): string {
    return this[0].toString();
  }

  get symbol(): string {
    return this[1].toString();
  }

  get projectId(): string {
    return this[2].toString();
  }

  get newProposalShare(): i32 {
    return this[3].toI32();
  }

  get minQuorum(): i32 {
    return this[4].toI32();
  }
}

export class ConfirmCreateGovernanceTokenCall extends ethereum.Call {
  get inputs(): ConfirmCreateGovernanceTokenCall__Inputs {
    return new ConfirmCreateGovernanceTokenCall__Inputs(this);
  }

  get outputs(): ConfirmCreateGovernanceTokenCall__Outputs {
    return new ConfirmCreateGovernanceTokenCall__Outputs(this);
  }
}

export class ConfirmCreateGovernanceTokenCall__Inputs {
  _call: ConfirmCreateGovernanceTokenCall;

  constructor(call: ConfirmCreateGovernanceTokenCall) {
    this._call = call;
  }

  get _requestId(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _result(): boolean {
    return this._call.inputValues[1].value.toBoolean();
  }
}

export class ConfirmCreateGovernanceTokenCall__Outputs {
  _call: ConfirmCreateGovernanceTokenCall;

  constructor(call: ConfirmCreateGovernanceTokenCall) {
    this._call = call;
  }
}

export class UpdateGovTokenParamsCall extends ethereum.Call {
  get inputs(): UpdateGovTokenParamsCall__Inputs {
    return new UpdateGovTokenParamsCall__Inputs(this);
  }

  get outputs(): UpdateGovTokenParamsCall__Outputs {
    return new UpdateGovTokenParamsCall__Outputs(this);
  }
}

export class UpdateGovTokenParamsCall__Inputs {
  _call: UpdateGovTokenParamsCall;

  constructor(call: UpdateGovTokenParamsCall) {
    this._call = call;
  }

  get _govToken(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _newProposalShare(): i32 {
    return this._call.inputValues[1].value.toI32();
  }

  get _minQuorum(): i32 {
    return this._call.inputValues[2].value.toI32();
  }
}

export class UpdateGovTokenParamsCall__Outputs {
  _call: UpdateGovTokenParamsCall;

  constructor(call: UpdateGovTokenParamsCall) {
    this._call = call;
  }
}
